Task1/PhoneApp/Models/ErrorViewModel.cs
namespace PhoneApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Task1/PhoneApp/Models/ExchangeRate.cs
namespace PhoneApp.Models
{
    public class ExchangeRate
    {
        public string CurrencyCode { get; set; }
        public string CurrencyName { get; set; }
        public double CurrencyRate { get; set; }
    }
}

Task1/PhoneApp/Models/MobileContext.cs
using Microsoft.EntityFrameworkCore;

namespace PhoneApp.Models
{
    public class MobileContext : DbContext

    {

        public DbSet<Phone> Phones { get; set; }

        public DbSet<Order> Orders { get; set; }



        public MobileContext(DbContextOptions<MobileContext> options)

            : base(options)

        {

        }
    }
}

Task1/PhoneApp/Models/Order.cs
namespace PhoneApp.Models
{
    public class Order
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Address { get; set; }

        public string ContactPhone { get; set; }



        public int PhoneId { get; set; }

        public Phone Phone { get; set; }
    }
}

Task1/PhoneApp/Models/Phone.cs
namespace PhoneApp.Models
{
    public class Phone
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Company { get; set; }
        public int Price { get; set; }
    }
}

Task1/PhoneApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PhoneApp.Models;
using System.Diagnostics;

namespace PhoneApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Task1/PhoneApp/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PhoneApp.Models;

namespace PhoneApp.Controllers
{
    public class OrdersController : Controller
    {
        private MobileContext _db;
        public OrdersController(MobileContext db)
        {
            _db = db;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var orders = _db.Orders.ToList();
            return View(orders);
        }

        [HttpGet]
        public IActionResult Add(int phoneId)
        {
            var phone = _db.Phones.FirstOrDefault(x => x.Id == phoneId);
            var order = new Order() {Phone = phone, PhoneId = phoneId};
            return View(order);
        }

        [HttpPost]
        public IActionResult Add(Order order)
        {
            if (order != null)
            {
                _db.Orders.Add(order);
                _db.SaveChanges();
            }
            return Redirect("Index");
        }
    }
}

Task1/PhoneApp/Controllers/PhonesController.cs
using Microsoft.AspNetCore.Mvc;
using PhoneApp.Models;

namespace PhoneApp.Controllers
{
    public class PhonesController : Controller
    {
        private MobileContext _db;
        public PhonesController(MobileContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            List<Phone> phones = _db.Phones.ToList();
            return View(phones);
        }
        public IActionResult Add() 
        {
            return View();
        }
        public IActionResult Company()
        {
            return Redirect("http://apple.com");
        }

        [HttpPost]
        public IActionResult Add(Phone phone)
        {
            if (phone != null)
            {
                _db.Phones.Add(phone);
                _db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Edit(int phoneId)
        {
            if (phoneId != null)
            {
                Phone phone = _db.Phones.FirstOrDefault(x => x.Id == phoneId);
                if (phone != null)
                {
                    return View(phone);
                }
            }
            return NotFound();
        }
        [HttpPost]
        public IActionResult Edit(Phone phone)
        {
            if (phone != null)
            {
                _db.Phones.Update(phone);
                _db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int phoneId)
        {
            if (phoneId != null)
            {
                Phone phone = _db.Phones.FirstOrDefault(x => x.Id == phoneId);
                if (phone != null)
                {
                    _db.Phones.Remove(phone);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return NotFound();
        }
    }
}

Task1/PhoneApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Task1/PhoneApp/Views/Orders/Add.cshtml
@model Order
@{
    ViewBag.Title = "Заказать смартфон";
}
<h2>Заполните форму для заказа</h2>
<div class="row">
    <div class="col-md-6">
        <form asp-action="Add" asp-controller="Orders" method="post">
            <div class="form-row mb-3">
                <label for="">
                    Имя покупателя
                    <input asp-for="Name" type="text">
                </label>
            </div>
            <div class="form-row mb-3">
                <label for="">
                    Адрес доставки
                    <input asp-for="Address" type="text">
                </label>
            </div>
            <div class="form-row mb-3">
                <label for="">
                    Номер телефона
                    <input asp-for="ContactPhone" type="text">
                </label>
            </div>
            <div class="form-row mb-3">
                <label for="">
                    Смартфон :
                    <input disabled type="text" value="@Model.Phone.Name">
                </label>
                <input asp-for="PhoneId" type="hidden" value="@Model.Phone.Id">
            </div>
            <button type="submit">Заказать</button>
        </form>
    </div>
</div>

Task1/PhoneApp/Views/Orders/Index.cshtml
@model List<Order>
@{
    ViewBag.Title = "Заказы";
}
<h2>Заказы</h2>
<div class="table_section">
    @if (@Model.Count == 0)
    {
        <p>Заказов ёщё не поступало</p>
    }
    else
    {
        <table style="width: 100%;">
            <tr>
                <th>Id</th>
                <th>Наименование</th>
                <th>Адрес</th>
                <th>Контактный телефон</th>
            </tr>
            @foreach (var order in @Model)
            {
                <tr>
                    <td>@order.Id</td>
                    <td>@order.Name</td>
                    <td>@order.Address</td>
                    <td>@order.ContactPhone</td>
                </tr>
            }
        </table>
    }
</div>

Task1/PhoneApp/Views/Phones/Add.cshtml
@model Phone
@{
    ViewBag.Title = "Добавить устройство";
}
<h2>Заполните форму для добавления устройства</h2>
<div class="row">
    <div class="phone_add_form">
        <form asp-action="Add" method="post">
            <div class="form_row mb-3">
                <label for="">
                    Наименование
                    <input asp-for="Name" type="text">
                </label>
            </div>
            <div class="form_row mb-3">
                <label for="">
                    Компания
                    <input asp-for="Company" type="text">
                </label>
            </div>
            <div class="form_row mb-3">
                <label for="">
                    Стоимость
                    <input asp-for="Price" type="text">
                </label>
            </div>
            <button type="submit">Создать</button>
        </form>
    </div>
</div>

Task1/PhoneApp/Views/Phones/Edit.cshtml
@model Phone
@{
    ViewBag.Title = "Редактирование";
}
<h2>Редактирование</h2>
<div class="row">
    <div class="col-md-6">
        <form asp-action="Edit" asp-controller="Phones" method="post">
            <input hidden asp-for="Id" value="@Model.Id">
            <div class="form_row">
                <label for="">
                    Наименование
                    <input asp-for="Name" type="text">
                </label>
            </div>
            <div class="form_row mb-3">
                <label for="">
                    Компания
                    <input asp-for="Company" type="text">
                </label>
            </div>
            <div class="form_row mb-3">
                <label for="">
                    Стоимость
                    <input asp-for="Price" type="text">
                </label>
            </div>
            <button type="submit">Изменить</button>
        </form>
    </div>
</div>

Task1/PhoneApp/Views/Phones/Index.cshtml
@model List<Phone>
@{
    ViewBag.Title = "Мобильные телефоны";
}
<h2>Мобильные телефоны</h2>
<a asp-action="Add" asp-controller="Phones">Добавить смартфон</a>
<div class="table_section">
    @if (@Model.Count == 0)
    {
        <p>Смартфоны еще не добавлены</p>
    }
    else
    {
        <table style="width: 100%;">
            <tr>
                <th>Id</th>
                <th>Наименование</th>
                <th>Компания</th>
                <th>Стоимость</th>
                <th>Действия</th>
                <th>Редактирование</th>
                <th>Сайт компании производителдя</th>
            </tr>
            @foreach (var phone in @Model)
            {
                <tr>
                    <td>@phone.Id</td>
                    <td>@phone.Name</td>
                    <td>@phone.Company</td>
                    <td>@phone.Price</td>
                    <td><a class="btn btn-dark" asp-controller="Orders" asp-action="Add" asp-route-phoneId="@phone.Id">Заказать</a></td>
                    <td><a class="btn btn-dark" asp-controller="Phones" asp-action="Edit" asp-route-phoneId="@phone.Id">Править</a>  |
                        <a class="btn btn-dark" asp-controller="Phones" asp-action="Delete" asp-route-phoneId="@phone.Id">Удалить</a>
                    </td>
                    <td><a class="btn btn-dark" asp-controller="Phones" asp-action="Company">Apple</a></td>
                </tr>
            }
        </table>
    }
</div>

Task1/PhoneApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PhoneApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PhoneApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PhoneApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Phones" asp-action="Index">Смартфоны</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Заказы</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PhoneApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>